#!/usr/bin/env bash

# Find custom files in the /config folder and copy them to the respective folders in /app. 
# Look for bridges that end in 'Bridge.php' and for the whitelist and config.ini files. Everything else is ignored
# This will overwrite previous configs and bridges. It also uses the default paths of the configs and bridges, so if there is no file that matches, rss-bridge works like default.
for f in `find /config/ -type f`; do
    fname=${f##*/}
    case $fname in
    *Bridge.php)    yes | cp $f /app/bridges/ ;
                    chown www-data:www-data /app/bridges/$fname;
                    printf "Custom Bridge %s added.\n" $fname;;
    config.ini.php) yes | cp $f /app/ ;
                    chown www-data:www-data /app/$fname;
                    printf "Custom config.ini.php added.\n";;
    whitelist.txt)  yes | cp $f /app/ ;
                    chown www-data:www-data /app/$fname;
                    printf "Custom whitelist.txt added.\n";;
    esac
done

# Start apache
apache2-foreground