name: Unit tests

on:
  push:
    branches: [ master, github-actions ]
  pull_request:
    branches: [ master ]

jobs:
  phpunit:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        php-versions: ['7.0', '7.1', '7.2', '7.3', '7.4']
        phpunit-versions: ['6.5.14', '7.5.20', '8.5.13']
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit:${{ matrix.phpunit-versions }}
      - run: phpunit --configuration=phpunit.xml --include-path=lib/
